// flow-typed signature: c1508d660902919f3f42a42cb453d020
// flow-typed version: <<STUB>>/react-native-datepicker_v1.7.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-datepicker/__tests__/Datepicker.test' {
  declare module.exports: any;
}

declare module 'react-native-datepicker/datepicker' {
  declare module.exports: any;
}

declare module 'react-native-datepicker/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-datepicker/__tests__/Datepicker.test.js' {
  declare module.exports: $Exports<'react-native-datepicker/__tests__/Datepicker.test'>;
}
declare module 'react-native-datepicker/datepicker.js' {
  declare module.exports: $Exports<'react-native-datepicker/datepicker'>;
}
declare module 'react-native-datepicker/style.js' {
  declare module.exports: $Exports<'react-native-datepicker/style'>;
}
