// flow-typed signature: ef3937269fa20d16ac6fe14780580c05
// flow-typed version: <<STUB>>/@react-navigation/native-stack_v^6.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/native-stack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/native-stack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/native-stack/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/navigators/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/types' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/DebugContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/DebugContainer.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/FontProcessor' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/FontProcessor.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/HeaderConfig' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/NativeStackView' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/navigators/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/types' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/DebugContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/DebugContainer.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/FontProcessor' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/FontProcessor.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/HeaderConfig' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/NativeStackView' {
  declare module.exports: any;
}

declare module '@react-navigation/native-stack/lib/module/views/NativeStackView.native' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/native-stack/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/navigators/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/navigators/createNativeStackNavigator'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/types.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/types'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/DebugContainer.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/DebugContainer'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/DebugContainer.native.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/DebugContainer.native'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/FontProcessor.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/FontProcessor'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/FontProcessor.native.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/FontProcessor.native'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/HeaderConfig.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/HeaderConfig'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/NativeStackView.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/NativeStackView'>;
}
declare module '@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native'>;
}
declare module '@react-navigation/native-stack/lib/module/index' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module'>;
}
declare module '@react-navigation/native-stack/lib/module/index.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module'>;
}
declare module '@react-navigation/native-stack/lib/module/navigators/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/navigators/createNativeStackNavigator'>;
}
declare module '@react-navigation/native-stack/lib/module/types.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/types'>;
}
declare module '@react-navigation/native-stack/lib/module/views/DebugContainer.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/DebugContainer'>;
}
declare module '@react-navigation/native-stack/lib/module/views/DebugContainer.native.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/DebugContainer.native'>;
}
declare module '@react-navigation/native-stack/lib/module/views/FontProcessor.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/FontProcessor'>;
}
declare module '@react-navigation/native-stack/lib/module/views/FontProcessor.native.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/FontProcessor.native'>;
}
declare module '@react-navigation/native-stack/lib/module/views/HeaderConfig.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/HeaderConfig'>;
}
declare module '@react-navigation/native-stack/lib/module/views/NativeStackView.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/NativeStackView'>;
}
declare module '@react-navigation/native-stack/lib/module/views/NativeStackView.native.js' {
  declare module.exports: $Exports<'@react-navigation/native-stack/lib/module/views/NativeStackView.native'>;
}
